export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE'

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'

export const ALL_USERS = 'ALL_USERS'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAILURE = 'ALL_USERS_FAILURE'

export const USER_BY_ID = 'USER_BY_ID'
export const USER_BY_ID_SUCCESS = 'USER_BY_ID_SUCCESS'

export const ADD_USER = 'ADD_USER'
export const SET_USER = 'SET_USER'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const REMOVE_USER = 'REMOVE_USER'
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS'
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const CLOSE_ORDER = 'CLOSE_ORDER'
export const CLOSE_ORDER_SUCCESS = 'CLOSE_ORDER_SUCCESS'
export const CLOSE_ORDER_FAILURE = 'CLOSE_ORDER_FAILURE'

export const ALL_ORDERS = 'ALL_ORDERS'
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS'
export const ALL_ORDERS_FAILURE = 'ALL_ORDERS_FAILURE'

export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILURE = 'GET_ORDER_FAILURE'

export const ALL_CATEGORIES = 'ALL_CATEGORIES'
export const ALL_CATEGORIES_SUCCESS = 'ALL_CATEGORIES_SUCCESS'
export const ALL_CATEGORIES_FAILURE = 'ALL_CATEGORIES_FAILURE'
